on:
  push:
    branches:
      - main

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: python
        run: python3 --version
      - name: next tag
        run: python3 .github/scripts/version-tag.py version
        id: next-tag
      - name: push tag
        env:
          TAG: ${{ steps.next-tag.outputs.TAG }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "${TAG}"
          git remote set-url origin "https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin "${TAG}"
          