on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: core.harbor.cicd-test-1.laigames.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_SECRET }}
      - run: echo core.harbor.cicd-test-1.laigames.net/cicd/server:${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: core.harbor.cicd-test-1.laigames.net/cicd/server:${{ github.ref_name }}
      - name: helm login
        uses: hiberbee/github-action-helm@latest
        with:
          helm: >
            helm registry login
            -u "${{ secrets.HARBOR_USER }}"
            -p "${{ secrets.HARBOR_SECRET }}"
            core.harbor.cicd-test-1.laigames.net
      - name: helm package
        uses: hiberbee/github-action-helm@latest
        with:
          helm: >
            upgrade package chart/
            --version ${{ github.ref_name }}
            --app-version ${{ github.ref_name }}
      - name: helm push
        uses: hiberbee/github-action-helm@latest
        with:
          helm: >
            helm push server-${{ github.ref_name }}.tgz
            oci://core.harbor.cicd-test-1.laigames.net/cicd/server-${{ github.ref_name }}.tgz
